name: Build and Deploy Code

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: print directory
        run: ls -la

  
  deploy:
  runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: deploying things
      - echo 'going to deploy'

# name: Build and Deploy Code

# on: [push, pull_request]

# jobs:
#   job1:
#     services:
#       postgres:
#         image: postgres
#         ports:
#           - 5432:5432
#         options: >-
#           --health-cmd pg_isready
#           --health-interval 10s
#           --health-timeout 5s
#           --health-retries 5

#     runs-on: ubuntu-latest
#     steps:
#       - name: pulling git repo
#         uses: actions/checkout@v2
#       - name: Install python version 3.9
#         uses: actions/setup-python@v2
#         with:
#           python-version: "3.9"
#       - name: update pip
#         run: python -m pip install --upgrade pip
#       - name: install all dependencies
#         run: pip install -r backend/requirements.txt
      # - name: test with pytest
      #   run: |
      #     pip install pytest
      #     pytest




